import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { BookOpen, ExternalLink, Copy } from "lucide-react";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

interface NotebookLinkProps {
  datasetId: string;
  datasetName: string;
}

export const NotebookLink = ({ datasetId, datasetName }: NotebookLinkProps) => {
  const { user } = useAuth();
  const [isOpen, setIsOpen] = useState(false);
  const [formData, setFormData] = useState({
    title: "",
    description: "",
  });

  const colabUrl = `https://colab.research.google.com/drive/new?dataset=${datasetId}`;
  
  const generateStarterCode = () => {
    return `# ${datasetName} - Starter Notebook
# Auto-generated by Juvana Platform

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset from Juvana
# Note: Replace with your actual dataset URL after uploading to Firebase Storage
DATASET_ID = "${datasetId}"
DATASET_URL = f"https://storage.googleapis.com/juvana-datasets/{DATASET_ID}/data.csv"

# Load data
try:
    df = pd.read_csv(DATASET_URL)
    print(f"Dataset loaded successfully! Shape: {df.shape}")
    print("\\nFirst few rows:")
    display(df.head())
except Exception as e:
    print(f"Error loading dataset: {e}")
    print("Please ensure the dataset is accessible and the URL is correct.")

# Basic exploration
print("\\nDataset Info:")
df.info()

print("\\nSummary Statistics:")
display(df.describe())

# Your analysis starts here
`;
  };

  const handleCreateNotebook = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      toast.error("Please sign in to create a notebook");
      return;
    }

    try {
      await addDoc(collection(db, "notebooks"), {
        title: formData.title,
        description: formData.description,
        datasetId,
        datasetName,
        userId: user.uid,
        userName: user.displayName || "Anonymous",
        userAvatar: user.photoURL,
        colabUrl,
        starterCode: generateStarterCode(),
        upvotes: 0,
        forkCount: 0,
        visibility: "public",
        createdAt: serverTimestamp(),
      });

      toast.success("Notebook created! Opening Google Colab...");
      window.open(colabUrl, "_blank");
      setIsOpen(false);
      setFormData({ title: "", description: "" });
    } catch (error) {
      console.error("Error creating notebook:", error);
      toast.error("Failed to create notebook");
    }
  };

  const copyStarterCode = () => {
    navigator.clipboard.writeText(generateStarterCode());
    toast.success("Starter code copied to clipboard!");
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button className="bg-gradient-to-r from-primary to-primary-glow">
          <BookOpen className="h-4 w-4 mr-2" />
          Open in Colab
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create Notebook with Google Colab</DialogTitle>
          <DialogDescription>
            Launch a new notebook pre-configured with this dataset
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="p-4 bg-muted rounded-lg space-y-2">
            <div className="flex items-center gap-2">
              <Badge variant="outline">Dataset</Badge>
              <span className="font-semibold">{datasetName}</span>
            </div>
            <p className="text-sm text-muted-foreground">
              Your notebook will include starter code to load and explore this dataset
            </p>
          </div>

          <form onSubmit={handleCreateNotebook} className="space-y-4">
            <div>
              <Label htmlFor="title">Notebook Title</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                placeholder={`${datasetName} Analysis`}
                required
              />
            </div>

            <div>
              <Label htmlFor="description">Description (Optional)</Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                placeholder="What will you explore in this notebook?"
                rows={3}
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-2">
                <Label>Starter Code Preview</Label>
                <Button type="button" variant="outline" size="sm" onClick={copyStarterCode}>
                  <Copy className="h-3 w-3 mr-1" />
                  Copy
                </Button>
              </div>
              <div className="p-4 bg-muted rounded-lg font-mono text-xs overflow-x-auto max-h-64 overflow-y-auto">
                <pre>{generateStarterCode()}</pre>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-4">
              <Button type="button" variant="outline" onClick={() => setIsOpen(false)}>
                Cancel
              </Button>
              <Button type="submit">
                <ExternalLink className="h-4 w-4 mr-2" />
                Open in Google Colab
              </Button>
            </div>
          </form>

          <div className="pt-4 border-t">
            <p className="text-sm text-muted-foreground">
              💡 <strong>Tip:</strong> You can also manually open{" "}
              <a href="https://colab.research.google.com" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
                Google Colab
              </a>{" "}
              and paste the starter code directly.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
